### ISSUE TITLE
'experimental protocol' is not a 'software'

### ISSUE THREAD

**Issue by bjonnh** [oxgiraldo/SMART-Protocols#3]
The fact that 'experimental protocol' 'has version' makes it a 'software' (because the domain of 'has version' is 'software').

**Comment by oxgiraldo** [comment]
In the ontology 'has version' has two domains "experimental protocol" (classified as a document), and "software". 



    <owl:ObjectProperty rdf:about="http://purl.org/pav/hasVersion">
        <rdfs:domain rdf:resource="http://purl.obolibrary.org/obo/ERO_0000071"/>
        <rdfs:domain rdf:resource="http://purl.org/net/SMARTprotocol#ExperimentalProtocol"/>
        <rdfs:range rdf:resource="http://purl.obolibrary.org/obo/IAO_0000129"/>
        <obo:IAO_0000412 xml:lang="en">PAV ontology</obo:IAO_0000412>
        <rdfs:label xml:lang="en">has version</rdfs:label>
    </owl:ObjectProperty>

Let me know if this is clear.

**Comment by bjonnh** [comment]
Which is exactly my problem.

According to RDFS specification and as explained here: https://stackoverflow.com/questions/23724182/rdfs-same-property-for-multiple-domains (and after a discussion on IRC on #swig with darkling):

What it means is that then an experimental protocol with a version is both an experimental protocol and a software. Which doesn't really make sense to me nor for this ontology.

The solution would be to have a software and experimental protocol as members of a super class. And assign the domain to that class.

**Comment by oxgiraldo** [comment]
I understand your concern and I agree. I am thinking about the best solution to address this problem. I will  let you know when a new version of the ontology is available.

**Comment by oxgiraldo** [comment]
Done. **software** and **experimental protocol** were classified as "information content entity". The domain of the property 'has version' was updated.
